name: .NET

on:
  push:

    branches: [ Dev ]



  pull_request:
    branches: [ master ]

jobs:
  build:
  

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
       
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Super-Linter
      uses: github/super-linter@v4.8.4
    - name: Install dependencies
      run: npm install
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tests:
    name: Unit Testing
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: dotnet test
      - run: Utility/ValidatorTests.cs
      - name: Test Reporter
  # You may pin to the exact commit or the version.
  # uses: dorny/test-reporter@0d00bb14cb0cc2c9b8985df6e81dd333188224e1
  uses: dorny/test-reporter@v1.5.0
  with:
    # Name or regex of artifact containing test results
    artifact: # optional
    # Name of the check run
    name:      

    reporter: 
    # Limits which test suites are listed. Supported options:
     - all
     - only-failed

    list-suites: # default is all
    # Limits which test cases are listed. Supported options:
    - all
    - only-failed
    - none

    list-tests: # default is all
    # Limits number of created annotations with error message and stack trace captured during test execution.
Must be less or equal to 50.

    max-annotations: # default is 10
    # Set this action as failed if test report contain any failed test
    fail-on-error: # default is true
    # Relative path under $GITHUB_WORKSPACE where the repository was checked out
    working-directory: # optional
    # Allows you to generate only the summary.
If enabled, the report will contain a table listing each test results file and the number of passed, failed, and skipped tests.
Detailed listing of test suites and test cases will be skipped.

    only-summary: # optional, default is false
    # GitHub Access Token
    token: # optional, default is ${{ github.token }}
    
      
   

